services:
  postgres:
    image: postgres:15
    container_name: postgres-chat
    restart: always
    environment:
      POSTGRES_DB: chat_auth
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cassandra:
    image: cassandra:latest
    container_name: cassandra-chat
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
volumes:
  postgres_data:
  cassandra_data: